import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopTealGlowBgWrapper from "@/components/Background/TopTealGlow";
import SmoothScrolling from "@/components/Layout/SmoothScrolling";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <SmoothScrolling>
          <TopTealGlowBgWrapper>{children}</TopTealGlowBgWrapper>
        </SmoothScrolling>
      </body>
    </html>
  );
}
